name: Deploy to VPS
on:
  push:
    branches: [ "main" ] # O "master", revisa c√≥mo se llama tu rama

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Creamos la carpeta si no existe
            mkdir -p ~/web-sobre-mi
            cd ~/web-sobre-mi
            
            # Si es la primera vez, clonamos. Si no, actualizamos.
            if [ ! -d ".git" ]; then
              git clone https://github.com/A-Goffard/Aintzane-Goffard.git .
            else
              git pull origin main
            fi
            
            # Levantamos Docker
            docker compose up -d --build --remove-orphans
            docker image prune -f